line-length = 88
src = ["app_api", "app_bot", "app_worker"]

[lint]
select = ["F", "E", "W", "I001"]
ignore = ["E501"]  # Skip line length violations

[format]
indent-style = "space"
quote-style = "single"
line-ending = "lf"
