[tool.ruff]
line-length = 88
lint.select = ["F", "E", "W", "I001"]
lint.ignore = ["E501"]  # Skip line length violations
src = ["app_api", "app_bot", "app_worker"]

[tool.ruff.format]
indent-style = "space"
quote-style = "single"
line-ending = "lf"
